@startmindmap
* DocHub
** Управление
*** Управление архитектурой
**** Инкрементальное развитие
*** Управление технологиями
**** Реестр технологий
*** Управление артефактами
**** Каталог артефактов
** Публикация
*** Автоматическая генерация
**** Диаграммы контекстов
**** Диаграммы аспектов
**** Карточки объектов
**** Технологический радар
*** Пользовательские артефакты
**** PlantUML
**** Markdown
***** Встраивание объектов DocHub
**** Swagger
@endmindmap
