@startmindmap
* DocHub
** Управление
*** Управление архитектурой
**** Манифесты компонентов
***** Инкрементальное развитие
****** GitLab
**** Манифесты контекстов
***** Инкрементальное развитие
****** GitLab
**** Манифесты аспектов
***** Инкрементальное развитие
****** GitLab
*** Управление технологиями
**** Манифесты технологий
***** Инкрементальное развитие
****** GitLab
*** Управление артефактами
**** Манифесты артефактов
***** Инкрементальное развитие
****** GitLab
** Публикация
*** Автоматическая генерация
**** Диаграммы контекстов
***** PlantUML
**** Диаграммы аспектов
***** PlantUML
**** Карточки объектов
**** Технологический радар
*** Пользовательские артефакты
**** Диаграммы, схемы и т.д.
***** PlantUML
**** Документы
***** Markdown
****** Встраивание объектов DocHub
**** API Контракты
***** Swagger
@endmindmap
