@startuml
{{#.}}
title {{title}}
{{#triggers}}
group {{#triggers}}{{.}}, {{/triggers}}
{{/triggers}}
    {{#steps}}
    "{{from}}" --> "{{to}}": {{#sub-interactions}}[[/entities/interactions/blank?id={{sub-interactions}} {{value}}]]{{/sub-interactions}}{{^sub-interactions}}{{value}}{{/sub-interactions}}
    {{/steps}}
    {{#results}}
    note across: {{#results}}{{.}}, {{/results}}
    {{/results}}
{{#triggers}}
end
{{/triggers}}

{{/.}}
@enduml
