@startwbs
* [[/entities/docs/blank?dh-doc-id=dochub.flex_metamodel.entities Примеры созданных пользовательских сущностей "Взаимодействия"]]
{{#.}}
{{#link}}
{{level}} [[{{&link}} {{title}}]]
{{/link}}
{{^link}}
{{level}} {{title}}
{{/link}}
{{/.}}
@endwbs
